//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentAPI.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaymentAPI.Resource.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount field is required.
        /// </summary>
        public static string Valid_Amount {
            get {
                return ResourceManager.GetString("Valid_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardHolder field is required.
        /// </summary>
        public static string Valid_CardHolder {
            get {
                return ResourceManager.GetString("Valid_CardHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card number is not valid!.
        /// </summary>
        public static string Valid_CCN {
            get {
                return ResourceManager.GetString("Valid_CCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Expiration date can not be in the past!.
        /// </summary>
        public static string Valid_Date {
            get {
                return ResourceManager.GetString("Valid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpirationDate not valid.
        /// </summary>
        public static string Valid_ExpirationDate {
            get {
                return ResourceManager.GetString("Valid_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a credit card number.
        /// </summary>
        public static string Valid_NotCCN {
            get {
                return ResourceManager.GetString("Valid_NotCCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code must be 3 digits!.
        /// </summary>
        public static string Valid_SecurityCode {
            get {
                return ResourceManager.GetString("Valid_SecurityCode", resourceCulture);
            }
        }
    }
}
