// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentAPI.DataBaseContext;

namespace PaymentAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210126122117_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentAPI.Models.Entities.PaymentEntitity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<string>("CardHolder");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CreditCardNumber");

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<int?>("PaymentStatusEntitiesID");

                    b.Property<string>("SecurityCode");

                    b.Property<int>("StatusID");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("ID");

                    b.HasAlternateKey("StatusID");

                    b.HasIndex("PaymentStatusEntitiesID");

                    b.ToTable("PaymentEntities");
                });

            modelBuilder.Entity("PaymentAPI.Models.Entities.PaymentStatusEntities", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PaymentState");

                    b.HasKey("ID");

                    b.ToTable("PaymentStatusEntities");
                });

            modelBuilder.Entity("PaymentAPI.Models.Entities.PaymentEntitity", b =>
                {
                    b.HasOne("PaymentAPI.Models.Entities.PaymentStatusEntities", "PaymentStatusEntities")
                        .WithMany("paymentEntitities")
                        .HasForeignKey("PaymentStatusEntitiesID");
                });
#pragma warning restore 612, 618
        }
    }
}
